#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: _TextStyle_Legal

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass _TextStyle_Legal._TextStyle_Legal_C
// 0x0000 (0x01A0 - 0x01A0)
class U_TextStyle_Legal_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"_TextStyle_Legal_C">();
	}
	static class U_TextStyle_Legal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<U_TextStyle_Legal_C>();
	}
};

}

