#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AthenaItemDetailsHeader

#include "Basic.hpp"

#include "AthenaItemDetailsHeader_classes.hpp"
#include "AthenaItemDetailsHeader_parameters.hpp"


namespace SDK
{

// Function AthenaItemDetailsHeader.AthenaItemDetailsHeader_C.UpdateRarityColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FFortColorPalette&         ColorPalette                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UAthenaItemDetailsHeader_C::UpdateRarityColor(const struct FFortColorPalette& ColorPalette)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaItemDetailsHeader_C", "UpdateRarityColor");

	Params::AthenaItemDetailsHeader_C_UpdateRarityColor Parms{};

	Parms.ColorPalette = std::move(ColorPalette);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaItemDetailsHeader.AthenaItemDetailsHeader_C.SetFortItemDetailsVM
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemDetailsVM*               ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UAthenaItemDetailsHeader_C::SetFortItemDetailsVM(class UFortItemDetailsVM* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaItemDetailsHeader_C", "SetFortItemDetailsVM");

	Params::AthenaItemDetailsHeader_C_SetFortItemDetailsVM Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}

}

