#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS27_CustomizationScreen

#include "Basic.hpp"

#include "BPS27_CustomizationScreen_classes.hpp"
#include "BPS27_CustomizationScreen_parameters.hpp"


namespace SDK
{

// Function BPS27_CustomizationScreen.BPS27_CustomizationScreen_C.ExecuteUbergraph_BPS27_CustomizationScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS27_CustomizationScreen_C::ExecuteUbergraph_BPS27_CustomizationScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS27_CustomizationScreen_C", "ExecuteUbergraph_BPS27_CustomizationScreen");

	Params::BPS27_CustomizationScreen_C_ExecuteUbergraph_BPS27_CustomizationScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS27_CustomizationScreen.BPS27_CustomizationScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBPS27_CustomizationScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS27_CustomizationScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

