#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ELockerScreenList

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ELockerScreenList.ELockerScreenList
// NumValues: 0x0006
enum class ELockerScreenList : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	ELockerScreenList_MAX                    = 5,
};

}

