#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FortGameplayGraph

#include "Basic.hpp"

#include "GameplayGraph_structs.hpp"


namespace SDK
{

// ScriptStruct FortGameplayGraph.SerializableConnectivityGraphVertex
// 0x0001 (0x0001 - 0x0000)
struct FSerializableConnectivityGraphVertex final
{
public:
	bool                                          bIsIndependentlySupported;                         // 0x0000(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct FortGameplayGraph.SerializableConnectivityGraph
// 0x0050 (0x0108 - 0x00B8)
struct FSerializableConnectivityGraph final : public FSerializableGraph
{
public:
	TMap<struct FGraphVertexHandle, struct FSerializableConnectivityGraphVertex> ConnectivityVertexData; // 0x00B8(0x0050)(SaveGame, NativeAccessSpecifierPublic)
};

}

