#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MPLoadoutTile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MPLoadoutTile.MPLoadoutTile_C
// 0x0010 (0x14A0 - 0x1490)
class UMPLoadoutTile_C final : public UCommonButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMPLoadoutCard_C*                       MPLoadoutCard;                                     // 0x1498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnListItemObjectSet(class UObject* ListItemObject);
	void ExecuteUbergraph_MPLoadoutTile(int32 EntryPoint);
	void BP_OnUnhovered();
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnHovered();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MPLoadoutTile_C">();
	}
	static class UMPLoadoutTile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMPLoadoutTile_C>();
	}
};

}

