#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: RufusRuntime

#include "Basic.hpp"

#include "RufusRuntime_classes.hpp"
#include "RufusRuntime_parameters.hpp"


namespace SDK
{

// Function RufusRuntime.FortPOIInjector.FortPlayerControllerEndingPlay
// (Final, Native, Protected)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortPOIInjector::FortPlayerControllerEndingPlay(class AActor* Actor, EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortPOIInjector", "FortPlayerControllerEndingPlay");

	Params::FortPOIInjector_FortPlayerControllerEndingPlay Parms{};

	Parms.Actor = Actor;
	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RufusRuntime.FortPOIInjector.HandleActorSpawned
// (Final, Native, Protected)
// Parameters:
// class AActor*                           SpawnedActor                                           (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortPOIInjector::HandleActorSpawned(class AActor* SpawnedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortPOIInjector", "HandleActorSpawned");

	Params::FortPOIInjector_HandleActorSpawned Parms{};

	Parms.SpawnedActor = SpawnedActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RufusRuntime.FortPOIInjector.HandleControllerComponentAttached
// (Final, Native, Protected)
// Parameters:
// class AFortPlayerController*            FortPlayerController                                   (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UFortControllerComponent*         ControllerComponent                                    (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortPOIInjector::HandleControllerComponentAttached(class AFortPlayerController* FortPlayerController, class UFortControllerComponent* ControllerComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortPOIInjector", "HandleControllerComponentAttached");

	Params::FortPOIInjector_HandleControllerComponentAttached Parms{};

	Parms.FortPlayerController = FortPlayerController;
	Parms.ControllerComponent = ControllerComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RufusRuntime.RufusWeeklyMapUpdater.OverrideDiscoverabilityTexture
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class UMaterialInstanceDynamic*         InStencilMID                                           (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARufusWeeklyMapUpdater::OverrideDiscoverabilityTexture(class UMaterialInstanceDynamic* InStencilMID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RufusWeeklyMapUpdater", "OverrideDiscoverabilityTexture");

	Params::RufusWeeklyMapUpdater_OverrideDiscoverabilityTexture Parms{};

	Parms.InStencilMID = InStencilMID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RufusRuntime.RufusWeeklyMapUpdater.SetActiveWeekByIndex
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InWeekIndex                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARufusWeeklyMapUpdater::SetActiveWeekByIndex(int32 InWeekIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RufusWeeklyMapUpdater", "SetActiveWeekByIndex");

	Params::RufusWeeklyMapUpdater_SetActiveWeekByIndex Parms{};

	Parms.InWeekIndex = InWeekIndex;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

