#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SparksCoreRuntime

#include "Basic.hpp"


namespace SDK
{

// Enum SparksCoreRuntime.ESparksInstrumentType
// NumValues: 0x0008
enum class ESparksInstrumentType : uint8
{
	Guitar                                   = 0,
	Bass                                     = 1,
	Vocals                                   = 2,
	Drum                                     = 3,
	Keyboard                                 = 4,
	None                                     = 5,
	NumInstrumentTypes                       = 5,
	ESparksInstrumentType_MAX                = 6,
};

// Enum SparksCoreRuntime.ESparksAccountItemSubtype
// NumValues: 0x000A
enum class ESparksAccountItemSubtype : uint8
{
	Aura                                     = 0,
	Guitar                                   = 1,
	Bass                                     = 2,
	Keyboard                                 = 3,
	Microphone                               = 4,
	Drums                                    = 5,
	SpotlightAnim                            = 6,
	None                                     = 7,
	NumAccountItemTypes                      = 7,
	ESparksAccountItemSubtype_MAX            = 8,
};

}

