#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TextStyleBaseSBT

#include "Basic.hpp"

#include "TextStyle_Base_S_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyleBaseSBT.TextStyleBaseSBT_C
// 0x0000 (0x01A0 - 0x01A0)
class UTextStyleBaseSBT_C final : public UTextStyle_Base_S_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyleBaseSBT_C">();
	}
	static class UTextStyleBaseSBT_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleBaseSBT_C>();
	}
};

}

