#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseNPC_0

#include "Basic.hpp"

#include "VerseAIBase_0_structs.hpp"
#include "VerseNPC_0_structs.hpp"
#include "EpicGamesTemporary_0_structs.hpp"
#include "VerseNative_structs.hpp"
#include "VerseFortnite_0_structs.hpp"


namespace SDK::Params
{

// Function VerseNPC.task_VerseNPC_npc_component$LootObject_L_Nfort__loot__info_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_LootObject_L_Nfort__loot__info_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$AttackObstacle_L_Nfort__obstacle__info_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_AttackObstacle_L_Nfort__obstacle__info_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fnavigatable_N_RGetCurrentDestination
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fnavigatable_N_RGetCurrentDestination final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TOptional<struct FSpatialMath_vector3>        RetVal;                                            // 0x0008(0x0020)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fnavigatable_N_RStopNavigation
// 0x0001 (0x0001 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fnavigatable_N_RStopNavigation final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__character__movement__interface_N_RStandUp
// 0x0002 (0x0002 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__character__movement__interface_N_RStandUp final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	EVerseAIBase_action_result                    RetVal;                                            // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RFire
// 0x0002 (0x0002 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RFire final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x0001(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash))
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RMeleeAttack
// 0x0002 (0x0002 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RMeleeAttack final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x0001(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash))
};

// Function VerseNPC.VerseNPC_npc_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RReload
// 0x0002 (0x0002 - 0x0000)
struct VerseNPC_npc_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__weapon__actions__interface_N_RReload final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x0001(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash))
};

// Function VerseNPC.VerseNPC_npc_component.AttackObstacle_L_Nfort__obstacle__info_R
// 0x0048 (0x0048 - 0x0000)
struct VerseNPC_npc_component_AttackObstacle_L_Nfort__obstacle__info_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVerseAIBase_fort_obstacle_info        __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0028)(Parm, NoDestructor)
	class Utask*                                  RetVal;                                            // 0x0040(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.AttackThreat_L_Ntarget__info_R
// 0x0050 (0x0050 - 0x0000)
struct VerseNPC_npc_component_AttackThreat_L_Ntarget__info_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAI_target_info                        __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0030)(Parm, NoDestructor)
	class Utask*                                  RetVal;                                            // 0x0048(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Crouch
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Crouch final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Jump
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Jump final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.LootObject_L_Nfort__loot__info_R
// 0x0048 (0x0048 - 0x0000)
struct VerseNPC_npc_component_LootObject_L_Nfort__loot__info_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVerseAIBase_fort_loot_info            __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0028)(Parm, NoDestructor)
	class Utask*                                  RetVal;                                            // 0x0040(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.MaintainFocus_L_Nagent_R
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_MaintainFocus_L_Nagent_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USimulation_agent*                      __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.MaintainFocus_L_Nvector3_R
// 0x0038 (0x0038 - 0x0000)
struct VerseNPC_npc_component_MaintainFocus_L_Nvector3_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSpatialMath_vector3                   __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class Utask*                                  RetVal;                                            // 0x0030(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.MoveInRangeToAttack
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_MoveInRangeToAttack final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.NavigateTo_L_Nnavigation__target_M_N_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R
// 0x0040 (0x0040 - 0x0000)
struct VerseNPC_npc_component_NavigateTo_L_Nnavigation__target_M_N_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R __verse_0xB2CDDD72_Argument; // 0x0018(0x0020)(Parm, HasGetValueTypeHash)
	class Utask*                                  RetVal;                                            // 0x0038(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.PlayEmote_L_Nemote_R
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_PlayEmote_L_Nemote_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAssets_emote*                          __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.PlayRandomEmote
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_PlayRandomEmote final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Revive_L_Nagent_R
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Revive_L_Nagent_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USimulation_agent*                      __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.RoamAround
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_RoamAround final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Slide
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Slide final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Sprint
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Sprint final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.TacticalSprint
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_TacticalSprint final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Wait_L_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R
// 0x0030 (0x0030 - 0x0000)
struct VerseNPC_npc_component_Wait_L_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TOptional<double>                             __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Utask*                                  RetVal;                                            // 0x0028(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_component.Walk
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_npc_component_Walk final
{
public:
	class Utask*                                  __verse_0xC1E81372_CallingTask;                    // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int64                                         __verse_0xA3A00DDB_CallerResumeState;              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int64                                         __verse_0x2AC0E4D8_CallerCancelState;              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0018(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class Utask*                                  RetVal;                                            // 0x0020(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$MaintainFocus_L_Nagent_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_MaintainFocus_L_Nagent_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$AttackThreat_L_Ntarget__info_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_AttackThreat_L_Ntarget__info_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$MaintainFocus_L_Nvector3_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_MaintainFocus_L_Nvector3_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Crouch.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Crouch_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Jump.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Jump_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$MoveInRangeToAttack.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_MoveInRangeToAttack_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$NavigateTo_L_Nnavigation__target_M_N_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_NavigateTo_L_Nnavigation__target_M_N_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$PlayEmote_L_Nemote_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_PlayEmote_L_Nemote_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$PlayRandomEmote.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_PlayRandomEmote_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Revive_L_Nagent_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Revive_L_Nagent_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$RoamAround.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_RoamAround_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Slide.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Slide_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Sprint.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Sprint_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$TacticalSprint.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_TacticalSprint_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Wait_L_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Wait_L_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.task_VerseNPC_npc_component$Walk.Update
// 0x0008 (0x0008 - 0x0000)
struct task_VerseNPC_npc_component_Walk_Update final
{
public:
	int64                                         RetVal;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RAddItemToInventory_L_Nfort__inventory__item__asset_M_Nint_R
// 0x0030 (0x0030 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RAddItemToInventory_L_Nfort__inventory__item__asset_M_Nint_R final
{
public:
	struct VerseNPC_0::Ftuple_Lfort__inventory__item__asset_Mint_R __verse_0xB2CDDD72_Argument;      // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
	TOptional<struct FVerseAIBase_fort_item_descriptor> RetVal;                                      // 0x0010(0x0020)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RDropItem_L_Nfort__item__descriptor_R
// 0x0020 (0x0020 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RDropItem_L_Nfort__item__descriptor_R final
{
public:
	struct FVerseAIBase_fort_item_descriptor      __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0018)(Parm, NoDestructor)
	uint8                                         RetVal : 1;                                        // 0x0018(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash))
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_REquipWeapon_L_Nfort__item__descriptor_R
// 0x0020 (0x0020 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_REquipWeapon_L_Nfort__item__descriptor_R final
{
public:
	struct FVerseAIBase_fort_item_descriptor      __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0018)(Parm, NoDestructor)
	TOptional<EVerseTrue>                         RetVal;                                            // 0x0018(0x0002)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetAllItems
// 0x0018 (0x0018 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetAllItems final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<struct FVerseAIBase_fort_item_descriptor> RetVal;                                         // 0x0008(0x0010)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetCurrentWeapon
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetCurrentWeapon final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TOptional<struct FVerseAIBase_fort_item_descriptor> RetVal;                                      // 0x0008(0x0020)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetWeaponDescriptor_L_Nfort__item__descriptor_R
// 0x0038 (0x0038 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RGetWeaponDescriptor_L_Nfort__item__descriptor_R final
{
public:
	struct FVerseAIBase_fort_item_descriptor      __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0018)(Parm, NoDestructor)
	TOptional<struct FVerseAIBase_fort_weapon_descriptor> RetVal;                                    // 0x0018(0x0020)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RIsWeaponEquipped_L_Nfort__item__descriptor_R
// 0x0020 (0x0020 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RIsWeaponEquipped_L_Nfort__item__descriptor_R final
{
public:
	struct FVerseAIBase_fort_item_descriptor      __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0018)(Parm, NoDestructor)
	uint8                                         RetVal : 1;                                        // 0x0018(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash))
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RRegisterUseSuggestedWeaponCallback_L_Nfort__item__descriptor_Tlogic_R
// 0x0018 (0x0018 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RRegisterUseSuggestedWeaponCallback_L_Nfort__item__descriptor_Tlogic_R final
{
public:
	FVerseFunctionProperty_                       __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
	int64                                         RetVal;                                            // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_inventory_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RUnregisterUseSuggestedWeaponCallback_L_Nint_R
// 0x0008 (0x0008 - 0x0000)
struct VerseNPC_inventory_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__inventory__interface_N_RUnregisterUseSuggestedWeaponCallback_L_Nint_R final
{
public:
	int64                                         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_leash_component._L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RClearLeash
// 0x0001 (0x0001 - 0x0000)
struct VerseNPC_leash_component__L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RClearLeash final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_leash_component._L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RSetLeashAgent_L_Nagent_M_Nfloat_M_Nfloat_R
// 0x0018 (0x0018 - 0x0000)
struct VerseNPC_leash_component__L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RSetLeashAgent_L_Nagent_M_Nfloat_M_Nfloat_R final
{
public:
	struct VerseNPC_0::Ftuple_Lagent_Mfloat_Mfloat_R __verse_0xB2CDDD72_Argument;                    // 0x0000(0x0018)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_leash_component._L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RSetLeashPosition_L_Nvector3_M_Nfloat_M_Nfloat_R
// 0x0028 (0x0028 - 0x0000)
struct VerseNPC_leash_component__L_2fFortnite_2ecom_2fAI_2ffort__leashable_N_RSetLeashPosition_L_Nvector3_M_Nfloat_M_Nfloat_R final
{
public:
	struct VerseNPC_0::Ftuple_Lvector3_Mfloat_Mfloat_R __verse_0xB2CDDD72_Argument;                  // 0x0000(0x0028)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component.$InitCDO
// 0x0140 (0x0140 - 0x0000)
struct VerseNPC_npc_perception_component__InitCDO final
{
public:
	class UVerseEngine_subscribable_event*        _ExprResult_0;                                     // 0x0000(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_1;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_2;                                     // 0x0010(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_3;                                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_4;                                     // 0x0020(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_5;                                // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_6;                                     // 0x0030(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_7;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_8;                                     // 0x0040(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_9;                                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_10;                                    // 0x0050(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_11;                               // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_12;                                    // 0x0060(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_13;                               // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_14;                                    // 0x0070(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_15;                               // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_16;                                    // 0x0080(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_17;                               // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_18;                                    // 0x0090(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_19;                               // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_20;                                    // 0x00A0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_21;                               // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_22;                                    // 0x00B0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_23;                               // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_24;                                    // 0x00C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_25;                               // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_26;                                    // 0x00D0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_27;                               // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_28;                                    // 0x00E0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_29;                               // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_30;                                    // 0x00F0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_31;                               // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_32;                                    // 0x0100(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_33;                               // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_34;                                    // 0x0110(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_35;                               // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_36;                                    // 0x0120(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_37;                               // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVerseEngine_subscribable_event*        _ExprResult_38;                                    // 0x0130(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint64                                        _InstancingGraph_39;                               // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RAlertLevelChangedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RAlertLevelChangedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RCurrentTargetChangedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RCurrentTargetChangedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetAlertLevel
// 0x0002 (0x0002 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetAlertLevel final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	EAI_guard_alert_level                         RetVal;                                            // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetAlertLevel_L_Ntarget__info_R
// 0x0038 (0x0038 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetAlertLevel_L_Ntarget__info_R final
{
public:
	struct FAI_target_info                        __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0030)(Parm, NoDestructor)
	EAI_guard_alert_level                         RetVal;                                            // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetCurrentTargetInfo
// 0x0040 (0x0040 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetCurrentTargetInfo final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TOptional<struct FAI_target_info>             RetVal;                                            // 0x0008(0x0038)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetDamageSettings_L_Nguard__alert__level_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetDamageSettings_L_Nguard__alert__level_R final
{
public:
	EAI_guard_alert_level                         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_damage_perception_settings*         RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetHearingSettings_L_Nguard__alert__level_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetHearingSettings_L_Nguard__alert__level_R final
{
public:
	EAI_guard_alert_level                         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_hearing_perception_settings*        RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetSightSettings_L_Nguard__alert__level_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetSightSettings_L_Nguard__alert__level_R final
{
public:
	EAI_guard_alert_level                         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_sight_perception_settings*          RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetTouchSettings_L_Nguard__alert__level_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RGetTouchSettings_L_Nguard__alert__level_R final
{
public:
	EAI_guard_alert_level                         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_touch_perception_settings*          RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetDamageSettings_L_Nguard__alert__level_M_Ndamage__perception__settings_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetDamageSettings_L_Nguard__alert__level_M_Ndamage__perception__settings_R final
{
public:
	struct VerseNPC_0::Ftuple_Lguard__alert__level_Mdamage__perception__settings_R __verse_0xB2CDDD72_Argument; // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetHearingSettings_L_Nguard__alert__level_M_Nhearing__perception__settings_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetHearingSettings_L_Nguard__alert__level_M_Nhearing__perception__settings_R final
{
public:
	struct VerseNPC_0::Ftuple_Lguard__alert__level_Mhearing__perception__settings_R __verse_0xB2CDDD72_Argument; // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetSightSettings_L_Nguard__alert__level_M_Nsight__perception__settings_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetSightSettings_L_Nguard__alert__level_M_Nsight__perception__settings_R final
{
public:
	struct VerseNPC_0::Ftuple_Lguard__alert__level_Msight__perception__settings_R __verse_0xB2CDDD72_Argument; // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetTouchSettings_L_Nguard__alert__level_M_Ntouch__perception__settings_R
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fguard__perception__interface_N_RSetTouchSettings_L_Nguard__alert__level_M_Ntouch__perception__settings_R final
{
public:
	struct VerseNPC_0::Ftuple_Lguard__alert__level_Mtouch__perception__settings_R __verse_0xB2CDDD72_Argument; // 0x0000(0x0010)(Parm, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDamageSettings
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDamageSettings final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_damage_perception_settings*         RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDetectedTarget_L_Nagent_R
// 0x0040 (0x0040 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDetectedTarget_L_Nagent_R final
{
public:
	class USimulation_agent*                      __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TOptional<struct FAI_target_info>             RetVal;                                            // 0x0008(0x0038)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDetectedTargets
// 0x0018 (0x0018 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetDetectedTargets final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<struct FAI_target_info>                RetVal;                                            // 0x0008(0x0010)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetHearingSettings
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetHearingSettings final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_hearing_perception_settings*        RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetSightSettings
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetSightSettings final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_sight_perception_settings*          RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetTouchSettings
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RGetTouchSettings final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UAI_touch_perception_settings*          RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetDamageSettings_L_Ndamage__perception__settings_R
// 0x0008 (0x0008 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetDamageSettings_L_Ndamage__perception__settings_R final
{
public:
	class UAI_damage_perception_settings*         __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetHearingSettings_L_Nhearing__perception__settings_R
// 0x0008 (0x0008 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetHearingSettings_L_Nhearing__perception__settings_R final
{
public:
	class UAI_hearing_perception_settings*        __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetSightSettings_L_Nsight__perception__settings_R
// 0x0008 (0x0008 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetSightSettings_L_Nsight__perception__settings_R final
{
public:
	class UAI_sight_perception_settings*          __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetTouchSettings_L_Ntouch__perception__settings_R
// 0x0008 (0x0008 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RSetTouchSettings_L_Ntouch__perception__settings_R final
{
public:
	class UAI_touch_perception_settings*          __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0008)(ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetAddedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetAddedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetHeardEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetHeardEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetInfoUpdatedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetInfoUpdatedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetRemovedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetRemovedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetSeenEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetSeenEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetTouchedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fperception__interface_N_RTargetTouchedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__loot__perception__interface_N_RBestObjectToLootChangedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__loot__perception__interface_N_RBestObjectToLootChangedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__loot__perception__interface_N_RGetBestObjectToLoot
// 0x0038 (0x0038 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__loot__perception__interface_N_RGetBestObjectToLoot final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TOptional<struct FVerseAIBase_fort_loot_info> RetVal;                                            // 0x0008(0x0030)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__obstacle__perception__interface_N_RGetObstacleInfo
// 0x0038 (0x0038 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__obstacle__perception__interface_N_RGetObstacleInfo final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TOptional<struct FVerseAIBase_fort_obstacle_info> RetVal;                                        // 0x0008(0x0030)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)
};

// Function VerseNPC.VerseNPC_npc_perception_component._L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__obstacle__perception__interface_N_RObstacleChangedEvent
// 0x0010 (0x0010 - 0x0000)
struct VerseNPC_npc_perception_component__L_2fFortnite_2ecom_2fAI_2fVerseAIBase_2ffort__obstacle__perception__interface_N_RObstacleChangedEvent final
{
public:
	struct VerseNPC_0::Ftuple_L_R                 __verse_0xB2CDDD72_Argument;                       // 0x0000(0x0001)(Parm, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                RetVal;                                            // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

}

