#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_Tile_CornerInfo

#include "Basic.hpp"

#include "WBP_Tile_CornerInfo_classes.hpp"
#include "WBP_Tile_CornerInfo_parameters.hpp"


namespace SDK
{

// Function WBP_Tile_CornerInfo.WBP_Tile_CornerInfo_C.SetCornerText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Tile_CornerInfo_C::SetCornerText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tile_CornerInfo_C", "SetCornerText");

	Params::WBP_Tile_CornerInfo_C_SetCornerText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tile_CornerInfo.WBP_Tile_CornerInfo_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Tile_CornerInfo_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tile_CornerInfo_C", "PreConstruct");

	Params::WBP_Tile_CornerInfo_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Tile_CornerInfo.WBP_Tile_CornerInfo_C.ExecuteUbergraph_WBP_Tile_CornerInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Tile_CornerInfo_C::ExecuteUbergraph_WBP_Tile_CornerInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Tile_CornerInfo_C", "ExecuteUbergraph_WBP_Tile_CornerInfo");

	Params::WBP_Tile_CornerInfo_C_ExecuteUbergraph_WBP_Tile_CornerInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

