#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_UIKit_ItemCard_Locker

#include "Basic.hpp"

#include "WBP_UIKit_ItemCard_Locker_classes.hpp"
#include "WBP_UIKit_ItemCard_Locker_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetItemIsArchived
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Is_Archived                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetItemIsArchived(bool Is_Archived)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetItemIsArchived");

	Params::WBP_UIKit_ItemCard_Locker_C_SetItemIsArchived Parms{};

	Parms.Is_Archived = Is_Archived;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetFortLockerCategoryItemVM
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortLockerCategoryItemVM*        ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetFortLockerCategoryItemVM(class UFortLockerCategoryItemVM* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetFortLockerCategoryItemVM");

	Params::WBP_UIKit_ItemCard_Locker_C_SetFortLockerCategoryItemVM Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetFortItemVM
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemVM*                      ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetFortItemVM(class UFortItemVM* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetFortItemVM");

	Params::WBP_UIKit_ItemCard_Locker_C_SetFortItemVM Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnListItemObjectSet");

	Params::WBP_UIKit_ItemCard_Locker_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.ExecuteUbergraph_WBP_UIKit_ItemCard_Locker
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::ExecuteUbergraph_WBP_UIKit_ItemCard_Locker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "ExecuteUbergraph_WBP_UIKit_ItemCard_Locker");

	Params::WBP_UIKit_ItemCard_Locker_C_ExecuteUbergraph_WBP_UIKit_ItemCard_Locker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnItemSelectionChanged");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnItemExpansionChanged");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_UIKit_ItemCard_Locker_C_BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_UIKit_ItemCard_Locker_C_BndEvt__WBP_UIKit_ItemCard_Locker_ItemCard_Base_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}

}

