#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_UIKit_Button_Selectable_TEMP_NOViewModel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_UIKit_ButtonGeneric_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UIKit_Button_Selectable_TEMP_NOViewModel.WBP_UIKit_Button_Selectable_TEMP_NOViewModel_C
// 0x0000 (0x1710 - 0x1710)
class UWBP_UIKit_Button_Selectable_TEMP_NOViewModel_C : public UWBP_UIKit_ButtonGeneric_Base_C
{
public:
	uint8                                         Pad_1702[0x6];                                     // 0x1702(0x0006)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_UIKit_Button_Selectable_TEMP_NOViewModel_C; // 0x1708(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void ExecuteUbergraph_WBP_UIKit_Button_Selectable_TEMP_NOViewModel(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetData(class UUIKitSelectableButtonViewModel* VM_Button);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UIKit_Button_Selectable_TEMP_NOViewModel_C">();
	}
	static class UWBP_UIKit_Button_Selectable_TEMP_NOViewModel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UIKit_Button_Selectable_TEMP_NOViewModel_C>();
	}
};

}

