#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_MPItemShop_Row

#include "Basic.hpp"

#include "WBP_MPItemShop_Row_classes.hpp"
#include "WBP_MPItemShop_Row_parameters.hpp"


namespace SDK
{

// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.UpdateTileSizes
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UFortItemShopOfferVM*>&    Offers                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_MPItemShop_Row_C::UpdateTileSizes(TArray<class UFortItemShopOfferVM*>& Offers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "UpdateTileSizes");

	Params::WBP_MPItemShop_Row_C_UpdateTileSizes Parms{};

	Parms.Offers = std::move(Offers);

	UObject::ProcessEvent(Func, &Parms);

	Offers = std::move(Parms.Offers);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ShowSubsectionHeaderSpacer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::ShowSubsectionHeaderSpacer(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ShowSubsectionHeaderSpacer");

	Params::WBP_MPItemShop_Row_C_ShowSubsectionHeaderSpacer Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ShowSubsectionHeader
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldShowHeader_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::ShowSubsectionHeader(bool ShouldShowHeader_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ShowSubsectionHeader");

	Params::WBP_MPItemShop_Row_C_ShowSubsectionHeader Parms{};

	Parms.ShouldShowHeader_0 = ShouldShowHeader_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ShowSectionHeader
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldShowHeader_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::ShowSectionHeader(bool ShouldShowHeader_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ShowSectionHeader");

	Params::WBP_MPItemShop_Row_C_ShowSectionHeader Parms{};

	Parms.ShouldShowHeader_0 = ShouldShowHeader_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ShouldShowHeader
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UFortItemShopSectionVM*           SectionVM                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_MPItemShop_Row_C::ShouldShowHeader(class UFortItemShopSectionVM* SectionVM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ShouldShowHeader");

	Params::WBP_MPItemShop_Row_C_ShouldShowHeader Parms{};

	Parms.SectionVM = SectionVM;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetTileNavigation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::SetTileNavigation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetTileNavigation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetSubheaderText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_MPItemShop_Row_C::SetSubheaderText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetSubheaderText");

	Params::WBP_MPItemShop_Row_C_SetSubheaderText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetRowWidth
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Width                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::SetRowWidth(double Width)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetRowWidth");

	Params::WBP_MPItemShop_Row_C_SetRowWidth Parms{};

	Parms.Width = Width;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetRowPeekState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInPeekState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::SetRowPeekState(bool IsInPeekState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetRowPeekState");

	Params::WBP_MPItemShop_Row_C_SetRowPeekState Parms{};

	Parms.IsInPeekState = IsInPeekState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetRowHitboxVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::SetRowHitboxVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetRowHitboxVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetRowActiveState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActiveState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::SetRowActiveState(bool IsActiveState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetRowActiveState");

	Params::WBP_MPItemShop_Row_C_SetRowActiveState Parms{};

	Parms.IsActiveState = IsActiveState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetParentHasFocusState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    HasFocus                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::SetParentHasFocusState(bool HasFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetParentHasFocusState");

	Params::WBP_MPItemShop_Row_C_SetParentHasFocusState Parms{};

	Parms.HasFocus = HasFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetHeaderText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_MPItemShop_Row_C::SetHeaderText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetHeaderText");

	Params::WBP_MPItemShop_Row_C_SetHeaderText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.SetFortItemShopOfferGroupVM
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemShopOfferGroupVM*        ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::SetFortItemShopOfferGroupVM(class UFortItemShopOfferGroupVM* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "SetFortItemShopOfferGroupVM");

	Params::WBP_MPItemShop_Row_C_SetFortItemShopOfferGroupVM Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ResetAllTiles
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::ResetAllTiles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ResetAllTiles");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.RequestMarkOfferGroupAsVisited
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::RequestMarkOfferGroupAsVisited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "RequestMarkOfferGroupAsVisited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.OnUpdateOffers
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UFortItemShopOfferVM*>&    OffersVM                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_MPItemShop_Row_C::OnUpdateOffers(TArray<class UFortItemShopOfferVM*>& OffersVM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "OnUpdateOffers");

	Params::WBP_MPItemShop_Row_C_OnUpdateOffers Parms{};

	Parms.OffersVM = std::move(OffersVM);

	UObject::ProcessEvent(Func, &Parms);

	OffersVM = std::move(Parms.OffersVM);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_MPItemShop_Row_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "OnRemovedFromFocusPath");

	Params::WBP_MPItemShop_Row_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_MPItemShop_Row_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "OnAddedToFocusPath");

	Params::WBP_MPItemShop_Row_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.MarkOfferGroupAsVisited
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::MarkOfferGroupAsVisited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "MarkOfferGroupAsVisited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.IsLastRowInSection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UFortItemShopSectionVM*           SectionVM                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_MPItemShop_Row_C::IsLastRowInSection(class UFortItemShopSectionVM* SectionVM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "IsLastRowInSection");

	Params::WBP_MPItemShop_Row_C_IsLastRowInSection Parms{};

	Parms.SectionVM = SectionVM;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.IsFirstRowInSection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UFortItemShopSectionVM*           SectionVM                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_MPItemShop_Row_C::IsFirstRowInSection(class UFortItemShopSectionVM* SectionVM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "IsFirstRowInSection");

	Params::WBP_MPItemShop_Row_C_IsFirstRowInSection Parms{};

	Parms.SectionVM = SectionVM;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.InitializeSubheader
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemShopSectionVM*           SectionVM                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::InitializeSubheader(class UFortItemShopSectionVM* SectionVM)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "InitializeSubheader");

	Params::WBP_MPItemShop_Row_C_InitializeSubheader Parms{};

	Parms.SectionVM = SectionVM;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.InitializeHeaders
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::InitializeHeaders()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "InitializeHeaders");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.GetTileByOfferId
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    OfferId                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UUserWidget**                     TileWidget                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::GetTileByOfferId(const class FString& OfferId, class UUserWidget** TileWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "GetTileByOfferId");

	Params::WBP_MPItemShop_Row_C_GetTileByOfferId Parms{};

	Parms.OfferId = std::move(OfferId);

	UObject::ProcessEvent(Func, &Parms);

	if (TileWidget != nullptr)
		*TileWidget = Parms.TileWidget;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.GetTileAtIndex
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUserWidget**                     TileWidget                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::GetTileAtIndex(int32 Index_0, class UUserWidget** TileWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "GetTileAtIndex");

	Params::WBP_MPItemShop_Row_C_GetTileAtIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (TileWidget != nullptr)
		*TileWidget = Parms.TileWidget;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.GetLastTileWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UUserWidget**                     LastTileWidget                                         (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::GetLastTileWidget(class UUserWidget** LastTileWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "GetLastTileWidget");

	Params::WBP_MPItemShop_Row_C_GetLastTileWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (LastTileWidget != nullptr)
		*LastTileWidget = Parms.LastTileWidget;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.GetFirstTile
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget**                     TileWidget                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::GetFirstTile(class UUserWidget** TileWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "GetFirstTile");

	Params::WBP_MPItemShop_Row_C_GetFirstTile Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TileWidget != nullptr)
		*TileWidget = Parms.TileWidget;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.GetDesiredFocusTile
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget**                     TileWidget                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::GetDesiredFocusTile(class UUserWidget** TileWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "GetDesiredFocusTile");

	Params::WBP_MPItemShop_Row_C_GetDesiredFocusTile Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TileWidget != nullptr)
		*TileWidget = Parms.TileWidget;
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.ExecuteUbergraph_WBP_MPItemShop_Row
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::ExecuteUbergraph_WBP_MPItemShop_Row(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "ExecuteUbergraph_WBP_MPItemShop_Row");

	Params::WBP_MPItemShop_Row_C_ExecuteUbergraph_WBP_MPItemShop_Row Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.CancelRequestMarkOfferGroupAsVisited
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::CancelRequestMarkOfferGroupAsVisited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "CancelRequestMarkOfferGroupAsVisited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.CalculateTileSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MPItemShop_Row_C::CalculateTileSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "CalculateTileSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Screen_Button_Crew_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Screen_Button_Crew_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Screen_Button_Crew_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_MPItemShop_Row_C_BndEvt__WBP_MPItemShop_Screen_Button_Crew_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Screen_Button_BattlePass_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Screen_Button_BattlePass_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Screen_Button_BattlePass_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_MPItemShop_Row_C_BndEvt__WBP_MPItemShop_Screen_Button_BattlePass_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Row_WBP_FillerButton_K2Node_ComponentBoundEvent_3_FillerButtonFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Row_WBP_FillerButton_K2Node_ComponentBoundEvent_3_FillerButtonFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Row_WBP_FillerButton_K2Node_ComponentBoundEvent_3_FillerButtonFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_MPItemShop_Row_C::BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "BndEvt__WBP_MPItemShop_Row_Button_RowHitbox_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MPItemShop_Row.WBP_MPItemShop_Row_C.__1c01b1a9-45ab-9040-3eb9-9dab19ca9413_SourceToDest
// (HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_MPItemShop_Row_C::__1c01b1a9_45ab_9040_3eb9_9dab19ca9413_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MPItemShop_Row_C", "__1c01b1a9-45ab-9040-3eb9-9dab19ca9413_SourceToDest");

	Params::WBP_MPItemShop_Row_C___1c01b1a9_45ab_9040_3eb9_9dab19ca9413_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

