#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_UIKit_Button_Tab

#include "Basic.hpp"

#include "WBP_UIKit_Button_Tab_classes.hpp"
#include "WBP_UIKit_Button_Tab_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_Button_Tab.WBP_UIKit_Button_Tab_C.UpdatePadding
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_UI_Alignment                          SelectionAlignment                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_Tab_C::UpdatePadding(E_UI_Alignment SelectionAlignment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_Tab_C", "UpdatePadding");

	Params::WBP_UIKit_Button_Tab_C_UpdatePadding Parms{};

	Parms.SelectionAlignment = SelectionAlignment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_Tab.WBP_UIKit_Button_Tab_C.UpdateAlignment
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_UI_Alignment                          Selection_Alignment                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_Tab_C::UpdateAlignment(E_UI_Alignment Selection_Alignment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_Tab_C", "UpdateAlignment");

	Params::WBP_UIKit_Button_Tab_C_UpdateAlignment Parms{};

	Parms.Selection_Alignment = Selection_Alignment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_Tab.WBP_UIKit_Button_Tab_C.SetSelectionAlignment
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_UI_Alignment                          Selection_Alignment                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_Tab_C::SetSelectionAlignment(E_UI_Alignment Selection_Alignment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_Tab_C", "SetSelectionAlignment");

	Params::WBP_UIKit_Button_Tab_C_SetSelectionAlignment Parms{};

	Parms.Selection_Alignment = Selection_Alignment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_Tab.WBP_UIKit_Button_Tab_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_Tab_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_Tab_C", "PreConstruct");

	Params::WBP_UIKit_Button_Tab_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_Tab.WBP_UIKit_Button_Tab_C.ExecuteUbergraph_WBP_UIKit_Button_Tab
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_Tab_C::ExecuteUbergraph_WBP_UIKit_Button_Tab(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_Tab_C", "ExecuteUbergraph_WBP_UIKit_Button_Tab");

	Params::WBP_UIKit_Button_Tab_C_ExecuteUbergraph_WBP_UIKit_Button_Tab Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

